pull_request_rules:
  - name: Automatic merge security PRs when all status checks pass
    conditions:
      - author~=^(dependabot\[bot\]|renovate\[bot\])$
      - status-success=tests (ubuntu-latest)
      - status-success=tests (macos-latest)
    actions:
      merge:
        method: rebase
      label:
        add:
          - mergify
