manifest:
  version: "0.10"
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
    - name: simensrostad
      url-base: https://github.com/simensrostad
  projects:
    - name: fw-nrfconnect-nrf
      path: nrf
      remote: simensrostad
      revision: agps-support-atv2-aws
      import: true
  self:
    path: firmware
