name: Update application source code from nRF Connect SDK

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    paths:
      - ".github/workflows/update-from-ncs.yaml"
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  CI_GITHUB_TOKEN: ${{ secrets.CI_GITHUB_TOKEN }}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove upstream files
        run: rm -rf ./{src,boards,child_image,tests}
      - name: Update from upstream
        run: |
          git clone --single-branch --branch agps-support-atv2-aws https://github.com/simensrostad/fw-nrfconnect-nrf sdk-nrf
          cp -rv sdk-nrf/applications/asset_tracker_v2/* ./
          echo "UPSTREAM_REV=`git -C sdk-nrf rev-parse HEAD | tr -d '\n'`" >> $GITHUB_ENV
          rm -rf sdk-nrf
      - name: Check if changes were made
        run: |
          if [[ `git status --porcelain` ]]; then
            echo "HAS_CHANGES=1" >> $GITHUB_ENV
          else
            echo "HAS_CHANGES=0" >> $GITHUB_ENV
          fi
      - name: Commit update
        if: env.HAS_CHANGES == '1'
        run: |
          echo "machine github.com login accesskey password ${GITHUB_TOKEN}" > ~/.netrc
          git config --global user.email "actions@example.com"
          git config --global user.name "GitHub Actions"
          git add -A
          git commit -m "fix: update from upstream

          See https://github.com/nrfconnect/sdk-nrf/tree/${{ env.UPSTREAM_REV }}/applications/asset_tracker_v2"
          git push
      - name: Trigger build
        if: env.HAS_CHANGES == '1'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.CI_GITHUB_TOKEN }}
          event-type: source-update
